name: HelloWorld-Workflow

on: 
  push:
    branches: 
      - master

jobs:
  hello:
    name: say hello
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Say Hello
        env:
          MSG: Hello World
        run: echo $MSG
