name: minimal Android CI workflow

on: 
  push:
    branches:
      - master

jobs:
  test:
    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: RunTests
        run: bash ./gradlew test --stacktrace
  
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-vava@v1
        with:
          java-version: 1.8
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/Upload-artifact@v1
        with:
          name: apk
          path: app/build/output/debug/app-debug.apk
